(define (problem BLOCKS-4-0)
(:domain BLOCKS)
(:objects A H G I - block)
(:INIT (ONTABLE I)
       (ON G H)
       (ON H A)
       (ON A I)
       (CLEAR G)
       (HANDEMPTY))
(:goal (AND (ON H A)
            (ON A G)
            (ON G I)))
)