(define (problem BLOCKS-4-0)
(:domain BLOCKS)
(:objects A B C D - block)
(:INIT (ONTABLE A)
       (ONTABLE B)
       (ONTABLE C)
       (ONTABLE D)
       (CLEAR A)
       (CLEAR B)
       (CLEAR C)
       (CLEAR D)
       (HANDEMPTY))
(:goal (AND (ON B A)
            (ON C B)
            (ON D C)))
)