(define (problem triangle-tire-1)
  (:domain triangle-tire)
  (:objects l1 l2 l3 l4 l5 l6 - location)
  (:init (vehicle-at l1)
		 (road l1 l2)
		 (road l2 l3)
		 (road l1 l4)
		 (road l2 l5)
		 (road l4 l2)
		 (road l5 l3)
		 (spare-in l4)
		 (spare-in l5)
		 (road l4 l6)
		 (road l6 l5)
		 (spare-in l6)
		 (spare-in l6)
		 (not-flattire))
  (:goal (vehicle-at l3)))
